export const API_PATHS = {
  auth: {
    login: (provider: "naver" | "kakao") => `/auth/${provider}`,
    logout: "/auth/logout",
    refresh: "/auth/refresh",
  },
  user: {
    base: "/user",
    profile: "/user/profile",
    publicProfile: (handle: string) => `/user/profile/${handle}`,
    stats: "/user/stats",
    wishlist: "/user/wishlist",
    wishlistCheck: "/user/wishlist/check",
  },
  book: {
    list: "/book-list",
    detail: "/book-detail",
    sales: "/book/sales",
    sale: "/book/sale",
    mySales: "/user/my-sales",
    saleStatus: (saleId: number) => `/book/sales/${saleId}/status`,
    saleDetail: (saleId: string) => `/book/sales/${saleId}`,
    saleForEdit: (saleId: string | number) => `/book/sales/${saleId}/edit`,
    relatedSales: (isbn: string) => `/book/${isbn}/sales`,
    updateSale: (saleId: number) => `/book/sales/${saleId}`,
    deleteSale: (saleId: number) => `/book/sales/${saleId}`,
    recentSales: "/book/sales/recent",
    popularBooks: "/book/popular",
    recordView: (isbn: string) => `/book/${isbn}/view`,
    summary: "/llm/book-summary",
    popularSales: "/book/sales/popular",
  },
  art: {
    list: "/art-list",
    detail: (artId: string) => `/art-detail/${artId}`,
  },
  chat: {
    rooms: "/chat/rooms",
    room: (roomId: number) => `/chat/rooms/${roomId}`,
    messages: (roomId: number) => `/chat/rooms/${roomId}/messages`,
    read: (roomId: number) => `/chat/rooms/${roomId}/read`,
  },
  comment: {
    base: "/comments",
    my: "/comments/my",
    detail: (id: number) => `/comments/${id}`,
    like: (id: number) => `/comments/${id}/like`,
  },
  readingLog: {
    base: "/reading-logs",
    stats: "/reading-logs/stats",
    list: "/reading-logs/list",
    settings: "/reading-logs/settings",
    detail: (id: string) => `/reading-logs/${id}`,
  },
  review: {
    base: "/reviews",
    detail: (id: number | string) => `/reviews/${id}`,
    edit: (id: number | string) => `/reviews/${id}/edit`,
    feeds: "/reviews/feeds",
    popular: "/reviews/popular",
    recommend: (id: number | string) => `/reviews/${id}/recommend`,
    myReaction: (id: number | string) => `/reviews/${id}/reaction`,
    toggleReaction: (id: number | string) => `/reviews/${id}/reactions`,
  },
  insights: {
    base: "/insights",
    locationSales: "/insights/location-sales",
  },
};
