export const PATHS = {
  HOME: "/",
  LOGIN: "/login",
  BOOK_SEARCH: "/book/search",
  BOOK_DETAIL: (isbn: string) => `/book/${isbn}/detail`,
  BOOK_SALES_REGISTER: "/book/sales/register",
  BOOK_SALES_DETAIL: (id: string) => `/book/sales/${id}`,
  ART_DETAIL: (id: string) => `/art/${id}`,
  MY_PAGE_SALES: "/my-page/sales",
  MY_PAGE_SALES_EDIT: (id: string) => `/my-page/sales/${id}/edit`,
  REVIEWS: "/book/reviews",
  REVIEW_WRITE: "/book/reviews/write",
  REVIEW_DETAIL: (id: string | number) => `/book/reviews/${id}`,
  REVIEW_EDIT: (id: string | number) => `/book/reviews/${id}/edit`,
  MY_PAGE: "/my-page",
  MY_REVIEWS: "/my-page/reviews",
  MY_COMMENTS: "/my-page/comments",
  MY_PAGE_WISHLIST: "/my-page/wishlist",
  BOOK_MARKET: "/book/market",
  USER_PROFILE: (id: number) => `/users/${id}`,
  INSIGHTS: "/insights",
} as const;
